version: '3.7'
services:
  flask:
    image: fergus98/flask:v2
    build: ./flask/
    ports:
    - target: 5000
      published: 5000
    deploy:
      replicas: 4
    networks:
    - my-network
  numbers:
    image: fergus98/numbers
    build: ./numbers/
    ports:
    - target: 5003
      published: 5003
    deploy:
      replicas: 4
    networks:
    - my-network
  letters:
    image: fergus98/letters
    build: ./letters/
    ports:
    - target: 5002
      published: 5002
    deploy: 
      replicas: 4
    networks:
    - my-network
  logic:
    image: fergus98/logic
    build: ./logic/
    ports:
    - target: 5001
      published: 5001
    deploy:
      replicas: 4
    networks:
    - my-network
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf
    networks:
    - my-network

networks:
  my-network:
