version: '3.7'
services:
  flask:
    image: fergus98/flask
    build: .
    ports:
    - target: 5000
      published: 5000
    deploy:
      replicas: 4
  numbers:
    image: fergus98/numbers
    build: .
    ports:
    - target: 5003
      published: 5003
    deploy:
      replicas: 4
  letters:
    image: fergus98/letters
    build: .
    ports:
    - target: 5002
      published: 5002
    deploy: 
      replicas: 4

