
- hosts: localhost
  connection: local
  tasks:
  - name: "generate key pair"
    openssh_keypair:
      path: ~/.ssh/id_rsa

- hosts: all
  become: true
  tasks:
  - name: prerequisites
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      state: latest
      update_cache: true
  - name: docker gpg key
    apt_key:
      url: "https://download.docker.com/linux/debian/gpg"
      state: present
  - name: docker apt repo
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/debian stretch stable"
      state: present
  - name: docker install
    apt:
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      state: latest
      update_cache: true
  - name: docker service
    service:
      name: docker
      state: started
  - name: "insecure registries"
    copy:
      src: /home/fergus/individual-project-2/daemon.json
      dest: /etc/docker/daemon.json
  - name: "reload docker"
    service:
      name: docker
      state: reloaded
- hosts: all
  become: true
  tasks:
  - name: jenkins user
    user:
      name: jenkins
      groups: 
      - docker
      append: true
      shell: /bin/bash
  
- name: Install Jenkins
  hosts: jenkins
  become: true
  tasks:
    - name: Install Java
      apt:
        name: openjdk-8-jdk
        state: present
        update_cache: yes
    - name: Download Jenkins Key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present
    - name: Import Jenkins Repo
      apt_repository:
        repo: deb http://pkg.jenkins.io/debian-stable binary/
        state: present
    - name: Apt Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes
    - name: Start & Enable Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: true
    - name: Sleep for 15 seconds and continue with play
      wait_for: timeout=15
    - name: insecure registry create Dir
      file:
        path: /etc/docker/
        state: directory
        mode: "0700"
    - name: insecure registry copy file
      copy:
        src: /home/fergus/individual-project-2/daemon.json
        dest: /etc/docker/daemon.json
        mode: u=rw,g=,o=
    - name: ssh folder
      file:
        path: /home/jenkins/.ssh
        state: directory
        mode: "0700"
        owner: jenkins
        group: jenkins
    - name: install private key
      copy:
        src: ~/.ssh/id_rsa
        dest: /home/jenkins/.ssh/id_rsa
        owner: jenkins
        group: jenkins
        mode: u=rw,g=,o=
    - name: Get init password Jenkins
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      changed_when: false
      register: result
    - name: Print init password Jenkins
      debug:
        var: result.stdout
    - name: Create a docker registry
      docker_container:
        name: registry
        image: registry
        ports:
          - "5000:5000"


- hosts: swarmmaster
  become: true
  tasks:
  - name: Initialize Docker Swarm
    shell: >
      docker swarm init
      --advertise-addr={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:2377
    #when: swarm_status.rc != 0
    run_once: true
    tags: swarm

  - name: Get the Manager join-token
    shell: docker swarm join-token --quiet manager
    register: manager_token
    tags: swarm

  - name: Get the worker join-token
    shell: docker swarm join-token --quiet worker
    register: worker_token
    tags: swarm

  #- name: Add Managers to the Swarm
   # shell: "docker swarm join --token {{ hostvars['51.145.13.187']['manager_token']['stdout'] }} {{ hostvars['51.145.13.187']['ansible_default_ipv4']['address'] }}:2377"
    #when: swarm_status.rc != 0
    #tags: swarm

- name: Add Worker
  hosts: swarmworker
  become: true
  tasks:
  - name: Add Workers to the Swarm
    shell: "docker swarm join --token {{ hostvars['51.104.226.110']['worker_token']['stdout'] }} {{ hostvars['51.104.226.110']['ansible_default_ipv4']['address'] }}:2377"
    tags: swarm

- name: Install docker public ssh key
  hosts: swarmmaster
  become: true
  tasks:
  - name: ssh folder
    file:
      path: /home/fergus/.ssh
      state: directory
      mode: "0700"
      owner: jenkins
      group: jenkins
  - name: install public key
    copy:
      src: ~/.ssh/id_rsa.pub
      dest: /home/fergus/.ssh/authorized_keys
      owner: jenkins
      group: jenkins
      mode: u=rw,g=,o=
