apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  labels:
    app: flask
spec:
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: fergus98/flask:latest
        ports:
        - name: flask-port
          containerPort: 5000


---

apiVersion: v1
kind: Service
metadata:
  name: flask
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: flask
